[build]
command = "npm run build -- --configuration stage"
publish = "dist/demo/browser"

[build.environment]
NODE_VERSION = "20"
REQUIRE_WEBPUSH_CONFIG = "true"

[[redirects]]
  from = "/api/*"
  to = "https://drmoghdamatest-10b-drsaeedtest2.runflare.cloud/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/hubs/*"
  to = "https://drmoghdamatest-10b-drsaeedtest2.runflare.cloud/hubs/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200