import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
@Component({selector:'app-header',standalone:true,imports:[RouterLink, RouterLinkActive],template:`
<header class="hdr">
  <a class="brand" routerLink="/">کلینیک دندانپزشکی دکتر سعید مقدم</a>
  <nav aria-label="ناوبری اصلی"><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact:true}">خانه</a><a routerLink="/services" routerLinkActive="active">خدمات</a><a routerLink="/about" routerLinkActive="active">درباره ما</a><a routerLink="/contact" routerLinkActive="active">تماس با ما</a></nav>
  <a class="cta" routerLink="/contact">رزرو مشاوره</a>
</header>`,styles:[`.hdr{position:sticky;top:0;z-index:10;width:min(1180px,calc(100% - 32px));margin:12px auto 0;background:rgba(255,253,248,.76);backdrop-filter:blur(22px);display:flex;align-items:center;justify-content:space-between;padding:10px 12px 10px 18px;border:1px solid rgba(133,109,84,.16);border-radius:999px;box-shadow:0 14px 40px rgba(57,42,30,.08)}.brand{font-size:14px;font-weight:900;color:#2e241d;white-space:nowrap}nav{display:flex;gap:4px;color:#5d5047}nav a{position:relative;padding:8px 12px;border-radius:999px;font-size:14px;font-weight:800;transition:background .2s ease,color .2s ease}nav a:hover,nav a.active{background:linear-gradient(135deg,rgba(223,243,255,.8),rgba(255,248,238,.82));color:#2e241d}.cta{position:relative;overflow:hidden;background:#211a16;color:white;padding:9px 15px;border-radius:999px;font-size:13px;font-weight:900;box-shadow:0 10px 24px rgba(33,26,22,.18)}.cta::after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(255,255,255,.22),transparent);transform:translateX(120%);transition:transform .55s ease}.cta:hover::after{transform:translateX(-120%)}@media(max-width:760px){.hdr{width:calc(100% - 20px);margin-top:8px;padding:9px 10px}.brand{font-size:13px;max-width:58%;overflow:hidden;text-overflow:ellipsis}nav{display:none}.cta{font-size:12px;padding:8px 12px}}`]} )
export class HeaderComponent {}
